/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kel4.minimarket911.auth;

import com.kel4.minimarket911.menu.MainMenu;

/**
 *
 * @author Acer
 */
public class FormLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLogin.class.getName());

    /**
     * Creates new form LoginForm
     */
    public FormLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kPanelLogin = new com.k33ptoo.components.KGradientPanel();
        kButton1 = new com.k33ptoo.components.KButton();
        lblJudul = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        customTextField3 = new com.kel4.minimarket911.component.CustomTextField();
        customTextField4 = new com.kel4.minimarket911.component.CustomTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));
        setSize(new java.awt.Dimension(640, 480));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        kPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        kPanelLogin.setkBorderRadius(20);
        kPanelLogin.setkEndColor(new java.awt.Color(42, 37, 54));
        kPanelLogin.setkStartColor(new java.awt.Color(42, 37, 54));
        kPanelLogin.setPreferredSize(new java.awt.Dimension(300, 350));
        kPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton1.setkAllowGradient(false);
        kButton1.setkBackGroundColor(new java.awt.Color(118, 97, 200));
        kButton1.setkBorderRadius(20);
        kButton1.setkHoverColor(new java.awt.Color(118, 97, 200));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkPressedColor(new java.awt.Color(87, 72, 148));
        kButton1.setLabel("Login");
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kButton1MouseEntered(evt);
            }
        });
        kButton1.addActionListener(this::kButton1ActionPerformed);
        kPanelLogin.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 240, -1));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("MiniMarket 9-Eleven");
        kPanelLogin.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 80));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(204, 204, 204));
        lblPassword.setText("Password");
        kPanelLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 70, -1));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(204, 204, 204));
        lblUsername.setText("Username");
        kPanelLogin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 90, 70, -1));

        customTextField3.setBackground(new java.awt.Color(58, 54, 73));
        customTextField3.setForeground(new java.awt.Color(255, 255, 255));
        customTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        customTextField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kel4/minimarket911/icon/icon-lock.png"))); // NOI18N
        customTextField3.setName(""); // NOI18N
        customTextField3.setPlaceholder("Password");
        kPanelLogin.add(customTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 192, 240, 50));

        customTextField4.setBackground(new java.awt.Color(58, 54, 73));
        customTextField4.setForeground(new java.awt.Color(255, 255, 255));
        customTextField4.setCaretColor(new java.awt.Color(255, 255, 255));
        customTextField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kel4/minimarket911/icon/icon-user.png"))); // NOI18N
        customTextField4.setName(""); // NOI18N
        customTextField4.setPlaceholder("Username");
        kPanelLogin.add(customTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 111, 240, 50));

        jPanel1.add(kPanelLogin, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        this.dispose();
        kButton1.setEnabled(false);
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseEntered
        
    }//GEN-LAST:event_kButton1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kel4.minimarket911.component.CustomTextField customTextField3;
    private com.kel4.minimarket911.component.CustomTextField customTextField4;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kPanelLogin;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
